# specify a list of ip providers
providers:
  - type: plain
    params:
      url: https://ipinfo.io/ip
  - type: plain
    params:
      url: https://api.ipify.org
  - type: plain
    params:
      url: https://ipecho.net/plain
  - type: plain
    params:
      url: https://ifconfig.me/ip
  # with basic auth
  - type: plain
    params:
      url: https://example.com/ip
      username: username
      password: password

# specify a list of dns updaters
updaters:
  - type: cloudflare
    params:
      zone_name: example.com
      record_type: A
      record_name: example.com
